apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: campus-mysql-pvc
  namespace: campus-studyroom
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: campus-mysql
  namespace: campus-studyroom
spec:
  serviceName: campus-mysql
  replicas: 1
  selector:
    matchLabels:
      app: campus-mysql
  template:
    metadata:
      labels:
        app: campus-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.36
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "campus_studyroom"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -p123456
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -p123456
            initialDelaySeconds: 60
            periodSeconds: 20
      volumes:
        - name: init-sql
          configMap:
            name: campus-mysql-init
        - name: mysql-data
          persistentVolumeClaim:
            claimName: campus-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: campus-mysql
  namespace: campus-studyroom
spec:
  selector:
    app: campus-mysql
  ports:
    - port: 3306
      targetPort: 3306
