kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: campus-k8s
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30081
        hostPort: 30081
        protocol: TCP
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://docker.m.daocloud.io", "https://docker.1ms.run", "https://docker.1panel.live", "https://dockerproxy.net", "https://hub.rat.dev", "https://docker.mirrors.ustc.edu.cn"]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
      endpoint = ["https://registry.cn-hangzhou.aliyuncs.com/google_containers"]
